## importing data set of digits---------------------------------------------------------

In [5]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
my_digits = load_digits()

In [6]:
dir(my_digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [7]:
my_digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
my_digits.target[5:8]

array([5, 6, 7])

In [9]:
my_digits.data[5:8]

array([[ 0.,  0., 12., 10.,  0.,  0.,  0.,  0.,  0.,  0., 14., 16., 16.,
        14.,  0.,  0.,  0.,  0., 13., 16., 15., 10.,  1.,  0.,  0.,  0.,
        11., 16., 16.,  7.,  0.,  0.,  0.,  0.,  0.,  4.,  7., 16.,  7.,
         0.,  0.,  0.,  0.,  0.,  4., 16.,  9.,  0.,  0.,  0.,  5.,  4.,
        12., 16.,  4.,  0.,  0.,  0.,  9., 16., 16., 10.,  0.,  0.],
       [ 0.,  0.,  0., 12., 13.,  0.,  0.,  0.,  0.,  0.,  5., 16.,  8.,
         0.,  0.,  0.,  0.,  0., 13., 16.,  3.,  0.,  0.,  0.,  0.,  0.,
        14., 13.,  0.,  0.,  0.,  0.,  0.,  0., 15., 12.,  7.,  2.,  0.,
         0.,  0.,  0., 13., 16., 13., 16.,  3.,  0.,  0.,  0.,  7., 16.,
        11., 15.,  8.,  0.,  0.,  0.,  1.,  9., 15., 11.,  3.,  0.],
       [ 0.,  0.,  7.,  8., 13., 16., 15.,  1.,  0.,  0.,  7.,  7.,  4.,
        11., 12.,  0.,  0.,  0.,  0.,  0.,  8., 13.,  1.,  0.,  0.,  4.,
         8.,  8., 15., 15.,  6.,  0.,  0.,  2., 11., 15., 15.,  4.,  0.,
         0.,  0.,  0.,  0., 16.,  5.,  0.,  0.,  0.,  0.,  

## creating dataframe and adding target column-------------------------------

In [10]:
df_digits = pd.DataFrame(my_digits.data)
df_digits.head()

0    1    2     3     4     5    6    7    8    9   ...   54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [11]:
df_digits['target']=my_digits.target
df_digits.head()

0    1    2     3     4     5    6    7    8    9  ...   55   56   57  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    58    59    60    61   62   63  target  
0  6.0  13.0  10.0   0.0  0.0  0.0       0  
1  0.0  11.0  16.0  10.0  0.0  0.0       1  
2  0.0   3.0  11.0  16.0  9.0  0.0       2  
3  7.0  13.0  13.0   9.0  0.0  0.0       3  
4  0.0   2.0  16.0   4.0  0.0  0.0       4  

[5 rows x 65 columns]

## Creating input and output variables---------------------------------------------

In [12]:
x = df_digits.drop(['target'], axis='columns')
y = df_digits.target

In [13]:
x.head(5)

0    1    2     3     4     5    6    7    8    9   ...   54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [14]:
y.head(5)

0    0
1    1
2    2
3    3
4    4
Name: target, dtype: int64

## Split data set into train and test set---------------------------------------------

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [20]:
x_train[50:55]

0    1     2     3     4     5    6    7    8    9   ...   54   55  \
1786  0.0  0.0   4.0  14.0  15.0   6.0  0.0  0.0  0.0  5.0  ...  6.0  0.0   
687   0.0  0.0   0.0   4.0  15.0  11.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
356   0.0  0.0   2.0  15.0  12.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1428  0.0  0.0  12.0  16.0  15.0   1.0  0.0  0.0  0.0  5.0  ...  7.0  0.0   
470   0.0  0.0  11.0  11.0   2.0   0.0  0.0  0.0  0.0  3.0  ...  9.0  0.0   

       56   57    58    59    60    61   62   63  
1786  0.0  0.0   4.0  13.0  15.0   9.0  0.0  0.0  
687   0.0  0.0   0.0   3.0  14.0   0.0  0.0  0.0  
356   0.0  0.0   6.0  16.0   5.0   0.0  0.0  0.0  
1428  0.0  0.0  10.0  16.0  16.0  10.0  1.0  0.0  
470   0.0  1.0  12.0  12.0  12.0  12.0  1.0  0.0  

[5 rows x 64 columns]

## Logistic Regression model---------------------------------------------------------

In [25]:
from sklearn.linear_model import LogisticRegression
model_lr = LogisticRegression(solver='newton-cg')

In [26]:
model_lr.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='newton-cg', tol=0.0001, verbose=0,
                   warm_start=False)

## Support Vector Model----------------------------------------------------------------

In [31]:
from sklearn.svm import SVC
model_svm = SVC()

In [ ]:
model_svm.fit(x_train,y_train)

## Random Forest Classifier-----------------------------------------------------------

In [33]:
from sklearn.ensemble import RandomForestClassifier
model_rfc = RandomForestClassifier()

In [ ]:
model_rfc.fit(x_train,y_train)

## Comparing scores---------------------------------------------------------------------

In [ ]:
model_lr.score(x_test,y_test)

In [ ]:
model_svm.score(x_test,y_test)

In [ ]:
model_rfc.score(x_test,y_test)

## Learning to use KFold----------------------------------------------------------------

In [ ]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

In [22]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [24]:
get_score(LogisticRegression(solver='newton-cg'),x_train,x_test,y_train,y_test)

0.9611111111111111

In [55]:
from sklearn.model_selection import StratifiedKFold
my_kfolds = StratifiedKFold(n_splits = 3)

In [46]:
scores_lr = []
scores_svm = []
scores_rfc = []

for train_index, test_index in my_kfolds.split(my_digits.data, my_digits.target):
    x_train,x_test,y_train,y_test = my_digits.data[train_index],\
                                    my_digits.data[test_index],\
                                    my_digits.target[train_index],\
                                    my_digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(solver='newton-cg'),x_train,x_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    scores_rfc.append(get_score(RandomForestClassifier(n_estimators=5),x_train,x_test,y_train,y_test))

In [47]:
print("Logistic Regression:")
print(scores_lr)
print("\nSupport vector Machine:")
print(scores_svm)
print("\nRandom Forest Classifier:")
print(scores_rfc)

Logistic Regression:
[0.9248747913188647, 0.9382303839732888, 0.9232053422370617]

Support vector Machine:
[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

Random Forest Classifier:
[0.8714524207011686, 0.8814691151919867, 0.8647746243739566]


## Using cross_val_score---------------------------------------------------------------

In [48]:
from sklearn.model_selection import cross_val_score

In [61]:
cross_val_score(LogisticRegression(solver="newton-cg"), my_digits.data, my_digits.target, cv=10)

array([0.90555556, 0.95555556, 0.88333333, 0.93333333, 0.93888889,
       0.95555556, 0.95      , 0.93296089, 0.88268156, 0.94413408])

#### change 'cv' to change number of folds used in model validation

In [58]:
cross_val_score(SVC(), my_digits.data, my_digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [59]:
cross_val_score(RandomForestClassifier(), my_digits.data, my_digits.target)

array([0.92222222, 0.90833333, 0.94707521, 0.95821727, 0.9275766 ])